// Mocks generated by Mockito 5.3.2 from annotations
// in ditonton/test/presentation/provider/tv_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/domain/entities/tv/tv.dart' as _i9;
import 'package:core/domain/entities/tv/tv_detail.dart' as _i7;
import 'package:core/domain/repositories/tv_repository.dart' as _i2;
import 'package:core/domain/usecases/tv/get_tv_detail.dart' as _i4;
import 'package:core/domain/usecases/tv/get_tv_recommendations.dart' as _i8;
import 'package:core/domain/usecases/tv/get_watchlist_tv_status.dart' as _i10;
import 'package:core/domain/usecases/tv/remove_watchlist_tv.dart' as _i12;
import 'package:core/domain/usecases/tv/save_watchlist_tv.dart' as _i11;
import 'package:core/utils/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvSerialRepository_0 extends _i1.SmartFake
    implements _i2.TvSerialRepository {
  _FakeTvSerialRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTvSerialDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSerialDetail extends _i1.Mock implements _i4.GetTvSerialDetail {
  MockGetTvSerialDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSerialRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvSerialRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvSerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvSerialDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.TvSerialDetail>>.value(
                _FakeEither_1<_i6.Failure, _i7.TvSerialDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.TvSerialDetail>>);
}

/// A class which mocks [GetTvSerialRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSerialRecommendations extends _i1.Mock
    implements _i8.GetTvSerialRecommendations {
  MockGetTvSerialRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSerialRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvSerialRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvSerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvSerial>>> execute(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvSerial>>>.value(
                _FakeEither_1<_i6.Failure, List<_i9.TvSerial>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.TvSerial>>>);
}

/// A class which mocks [GetWatchListTvSerialStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListTvSerialStatus extends _i1.Mock
    implements _i10.GetWatchListTvSerialStatus {
  MockGetWatchListTvSerialStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSerialRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvSerialRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvSerialRepository);
  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveWatchlistTvSerial].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTvSerial extends _i1.Mock
    implements _i11.SaveWatchlistTvSerial {
  MockSaveWatchlistTvSerial() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSerialRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvSerialRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvSerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvSerialDetail? tvSerial) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tvSerial],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tvSerial],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTvSerial].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvSerial extends _i1.Mock
    implements _i12.RemoveWatchlistTvSerial {
  MockRemoveWatchlistTvSerial() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvSerialRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvSerialRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvSerialRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvSerialDetail? tvSerial) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tvSerial],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tvSerial],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
